import type { CodolioSignals } from './types';
import { buildCard } from './scoring';
import type { Card } from './types';

const SAMPLE_SIGNALS: CodolioSignals[] = [
  {
    username: 'CodeMaster99',
    name: 'Arjun Patel',
    avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=ArjunPatel&backgroundColor=b6e3f4',
    totalSolved: 1820,
    easySolved: 480,
    mediumSolved: 920,
    hardSolved: 420,
    platforms: 4,
    contestRating: 2150,
    contestsAttended: 85,
    currentStreak: 180,
    maxStreak: 365,
    languages: 8,
    contributions: 1200,
    reputation: 3500,
  },
  {
    username: 'AlgoQueen',
    name: 'Priya Sharma',
    avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=PriyaSharma&backgroundColor=ffd5dc',
    totalSolved: 650,
    easySolved: 200,
    mediumSolved: 350,
    hardSolved: 100,
    platforms: 3,
    contestRating: 1650,
    contestsAttended: 35,
    currentStreak: 45,
    maxStreak: 90,
    languages: 5,
    contributions: 450,
    reputation: 800,
  },
  {
    username: 'ByteNinja',
    name: 'Rahul Dev',
    avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=RahulDev&backgroundColor=c0aede',
    totalSolved: 280,
    easySolved: 120,
    mediumSolved: 130,
    hardSolved: 30,
    platforms: 2,
    contestRating: 1200,
    contestsAttended: 12,
    currentStreak: 14,
    maxStreak: 30,
    languages: 3,
    contributions: 80,
    reputation: 150,
  },
  {
    username: 'SolveKing',
    name: 'Vikram Singh',
    avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=VikramSingh&backgroundColor=d1f4cc',
    totalSolved: 1200,
    easySolved: 350,
    mediumSolved: 620,
    hardSolved: 230,
    platforms: 5,
    contestRating: 1900,
    contestsAttended: 60,
    currentStreak: 95,
    maxStreak: 200,
    languages: 7,
    contributions: 850,
    reputation: 2100,
  },
  {
    username: 'DataWiz',
    name: 'Ananya Roy',
    avatarUrl: 'https://api.dicebear.com/8.x/avataaars/svg?seed=AnanyaRoy&backgroundColor=ffdfbf',
    totalSolved: 430,
    easySolved: 180,
    mediumSolved: 200,
    hardSolved: 50,
    platforms: 3,
    contestRating: 1450,
    contestsAttended: 22,
    currentStreak: 30,
    maxStreak: 60,
    languages: 4,
    contributions: 200,
    reputation: 450,
  },
];

export function getSampleCards(): Card[] {
  return SAMPLE_SIGNALS.map(buildCard);
}
